services:
  db:
    image: mysql:8.0
    container_name: community_mysql
    environment:
      MYSQL_DATABASE: community
      MYSQL_USER: community_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
